import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "선바로(Sunbaro) IR Deck 2025",
    category: "스타트업 IR / 제조",
    categoryColorClass: "text-indigo-400 bg-indigo-900/50",
    description: "4년간의 시공 현장 경험을 바탕으로 개발된 일체형 전선 몰딩 '선바로'의 IR 자료입니다. 기존 제품의 한계(재시공 문제)를 해결하는 기술력과 B2B/B2C를 아우르는 비즈니스 모델을 투자자에게 명확히 전달하는 데 주력했습니다.",
    shortDesc: "일체형 전선 몰딩과 다양한 연결캡으로 시공 효율을 높이는 선바로의 사업 계획서를 현장의 문제점과 해결책을 명확히 시각화",
    role: "PPT 기획 및 디자인 100%",
    tools: "PowerPoint, Photoshop, Illustrator",
    contribution: 100,
    tags: ["IR Pitch Deck", "Manufacturing", "B2B"],
    solutions: [
      "<b>Flow:</b> 문제인식(Why) -> 실현가능성(What) -> 성장전략(How)의 논리적 스토리라인 구축",
      "<b>Visualization:</b> 일체형 구조와 2중 인서트 공법 등 제품의 핵심 기술을 3D 상세 이미지와 비교 컷으로 직관적 표현",
      "<b>Data Design:</b> 복잡한 시장 규모(TAM-SAM-SOM)와 매출 데이터를 브랜드 컬러인 블루를 활용하여 깔끔하게 도식화"
    ],
    thumbnail: "https://i.ibb.co/WvD5WxWG/sunbaro-12.png",
    beforeImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMTgx/MDAxNzcwNzA5OTkxMTM5.Me2Q0n6NBvky-uV8C92S2u-s41bw-gfEhf9DO42P6-kg.uPqoe0rwZtwj6bC5Z2YfkYbikjV51bzQDxGKmzFDUTQg.PNG/image.png?type=w966",
    afterImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMTA4/MDAxNzcwNzEwMDExMzE3.eLTqfUgesuQrGqS0NVDPWY4onMSuHYppnEOcLz0E8dog.04twCKSw2fkgndqDQtAHU0tvAOcRrWBSlJ7ICuJMed0g.PNG/image.png?type=w966",
    galleryColorClass: "text-indigo-500",
    galleryImages: [
      "https://i.ibb.co/MygQhZV6/sunbaro-11.png",
      "https://i.ibb.co/mrvhp0YQ/sunbaro-10.png",
      "https://i.ibb.co/yc66BYCP/sunbaro-9.png",
      "https://i.ibb.co/Zsx6S1t/sunbaro-8.png",
      "https://i.ibb.co/wrwW3WhQ/sunbaro-7.png",
      "https://i.ibb.co/qMgzjqQF/sunbaro-6.png",
      "https://i.ibb.co/7d6fYFc7/sunbaro-5.png",
      "https://i.ibb.co/yntVYVz9/sunbaro-4.png",
      "https://i.ibb.co/672p9ms8/sunbaro-3.png",
      "https://i.ibb.co/4Rr6xjk7/sunbaro-2.png",
      "https://i.ibb.co/qFj4KT4c/sunbaro-1.png"
    ]
  },
  {
    id: 2,
    title: "ExMo 헬스케어 플랫폼 소개서",
    category: "헬스케어 / 플랫폼",
    categoryColorClass: "text-cyan-400 bg-cyan-900/50",
    description: "다중 센서 기반의 동작 분석 및 진단 시스템 'ExMo'의 서비스 소개서입니다. 복잡한 의료/헬스케어 데이터를 대시보드 형태의 UI 디자인으로 풀어내어 전문성과 신뢰도를 높였습니다.",
    shortDesc: "다중 센서 기반의 동작 분석 및 진단 시스템 ExMo의 서비스 소개서를 기술적 우위와 비즈니스 모델을 명확한 인포그래픽으로 표현",
    role: "PPT 기획 및 디자인 100%",
    tools: "PowerPoint, Photoshop, Illustrator",
    contribution: 100,
    tags: ["Healthcare", "Platform", "Data Viz"],
    solutions: [
      "<b>Visual Hierarchy:</b> '문제 제기 - 솔루션 - 기대 효과'의 흐름을 아이콘과 도식화로 명확히 구분",
      "<b>UI/UX Design:</b> 실제 서비스 화면을 시뮬레이션한 대시보드 디자인으로 개발 가능성 시각화",
      "<b>Color Strategy:</b> 의료 분야의 신뢰를 주는 Blue & Mint 컬러 시스템 적용"
    ],
    thumbnail: "https://i.ibb.co/fYnPHhbr/exmo-11.png",
    beforeImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMjQ1/MDAxNzcwNzEzMzc2ODgx.qyd2gWfK-7iUsL4RL-se5Bgp3dWTlvSKftAklFNU52Mg.5xRm4Mtl82Ol2YUExc-2CG5ccO9JojGcYw8c_D1HYzog.PNG/image.png?type=w966",
    afterImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMjkg/MDAxNzcwNzExNTMxNjM5.WNLVebtTDRscsb_ai7DE_hzAKTWCulz7XoDf3zwsBIgg.nfHi72AbNV5kMJdNe31-tM--PCxf6BYFJzqCuJAJWgQg.PNG/222.png?type=w966",
    galleryColorClass: "text-cyan-500",
    galleryImages: [
      "https://i.ibb.co/bgkhscJg/exmo-10.png",
      "https://i.ibb.co/9RhQFJD/exmo-9.png",
      "https://i.ibb.co/0pGzRxVc/exmo-8.png",
      "https://i.ibb.co/BHS0C1Jx/exmo-7.png",
      "https://i.ibb.co/FLbm7zDG/exmo-6.png",
      "https://i.ibb.co/JFs08fN5/exmo-5.png",
      "https://i.ibb.co/p6RZLK8Y/exmo-4.png",
      "https://i.ibb.co/LMN7Lrp/exmo-3.png",
      "https://i.ibb.co/B5vQPGkK/exmo-2.png",
      "https://i.ibb.co/LXLQKmx6/exmo-1.png"
    ]
  },
  {
    id: 3,
    title: "인더스트리얼 AI B2B 제안서",
    category: "B2B / AI Tech",
    categoryColorClass: "text-yellow-500 bg-yellow-900/50",
    description: "\"AI가 공장의 마지막 수작업을 지웁니다\" 스마트팩토리 AI 솔루션의 복잡한 기술을 직관적인 3D 그래픽으로 시각화",
    shortDesc: "\"AI가 공장의 마지막 수작업을 지웁니다\" 스마트팩토리 AI 솔루션의 복잡한 기술을 직관적인 3D 그래픽으로 시각화",
    role: "PPT 기획 및 디자인 100%",
    tools: "PowerPoint, Photoshop, Illustrator",
    contribution: 100,
    tags: ["Smart Factory", "B2B", "AI Tech"],
    solutions: [
      "<b>Catchphrase:</b> \"AI가 공장의 마지막 수작업을 지웁니다\"라는 강력한 슬로건으로 오프닝 장악",
      "<b>Tone & Manner:</b> 어두운 공장을 밝히는 기술을 상징하는 Black & Gold 컬러 시스템 구축",
      "<b>Diagram:</b> 복잡한 HW/SW 결합 구조를 비전문가도 이해하기 쉬운 도식으로 단순화"
    ],
    thumbnail: "https://i.ibb.co/rRGxr6pZ/aiindustrial-17.png",
    beforeImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMTIw/MDAxNzcwNzE0MDQ1NDE4.-GZfoIZpiKv9Yb3iUjSu3hc1vjQckjvRGdh7gecZ-JIg.RVhy9l9aEDIFV09rcr9BakvtqYLeEs1jOtNMdPvcTEcg.PNG/image.png?type=w966",
    afterImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMjQ0/MDAxNzcwNzExOTU0MDE4.lBfDeLhNR3Vc2vbysgvAi2eKss13f6Phvsky3FUAvHUg.aaxxKntgaQK7k4dpIElCqw0Wk_7yrp1Y9ZjzJiDYr_8g.PNG/10.png?type=w966",
    galleryColorClass: "text-yellow-500",
    galleryImages: [
      "https://i.ibb.co/hFWGYrp7/aiindustrial-16.png",
      "https://i.ibb.co/wN7Gy0DJ/aiindustrial-15.png",
      "https://i.ibb.co/WNwpRf6X/aiindustrial-14.png",
      "https://i.ibb.co/8gRywN5X/aiindustrial-13.png",
      "https://i.ibb.co/Lhkr0FpD/aiindustrial-12.png",
      "https://i.ibb.co/TxWPbzmw/aiindustrial-11.png",
      "https://i.ibb.co/fV2tKvnj/aiindustrial-10.png",
      "https://i.ibb.co/rLhYH0Q/aiindustrial-9.png",
      "https://i.ibb.co/7T6GNtV/aiindustrial-8.png",
      "https://i.ibb.co/NdbbY2gb/aiindustrial-7.png",
      "https://i.ibb.co/62zFYYF/aiindustrial-6.png",
      "https://i.ibb.co/ns0SqvXj/aiindustrial-5.png",
      "https://i.ibb.co/SDVwtpTF/aiindustrial-4.png",
      "https://i.ibb.co/sdTnJxXb/aiindustrial-3.png",
      "https://i.ibb.co/gZ5Vmv1q/aiindustrial-2.png",
      "https://i.ibb.co/Y7BWVy2m/aiindustrial-1.png"
    ]
  },
  {
    id: 4,
    title: "SEAFLOW 해양 정보 플랫폼 IR",
    category: "플랫폼 IR",
    categoryColorClass: "text-blue-400 bg-blue-900/50",
    description: "해양 레저 및 산업을 위한 3차원 해양 정보 데이터 플랫폼 'SEAFLOW'의 IR 자료입니다. 해양 데이터의 중요성과 기술력을 직관적인 인포그래픽으로 시각화하여 사업의 비전을 명확히 전달했습니다.",
    shortDesc: "해양 레저 및 산업을 위한 3차원 해양 정보 데이터 플랫폼의 복잡한 해양 데이터를 시각화하고 비즈니스 모델을 명확히 제시",
    role: "PPT 기획 및 디자인 100%",
    tools: "PowerPoint, Photoshop, Illustrator",
    contribution: 100,
    tags: ["Marine Tech", "Platform", "IR Pitch Deck"],
    solutions: [
      "<b>Visualization:</b> 문제점(텍스트) -> 솔루션(3차원 시각화)의 극적인 변화를 카드형 UI로 디자인",
      "<b>Iconography:</b> 해양 산업의 복잡한 카테고리를 직관적인 아이콘으로 분류하여 정보 전달력 강화",
      "<b>Color Strategy:</b> 깊이감 있는 블루 컬러를 사용하여 전문성과 신뢰감 형성"
    ],
    thumbnail: "https://i.ibb.co/5xK4sMvR/seaflow-19.png",
    beforeImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMTY3/MDAxNzcwNzE0NDg0NTgz.9e3YajoCGLNcbIY2kBN83_uADVY9rut0oRvRD52J9DAg.OIzGeP3-5sZja-VXgtKO_raBl4JHzHEhKQI6B6br5pUg.PNG/image.png?type=w966",
    afterImg: "https://postfiles.pstatic.net/MjAyNjAyMTBfMTg3/MDAxNzcwNzExNzg2NjQx.hwah-PwuDGGMY7Y5_hTgoqBSqrWzAsxL1Mpqjg2FxRsg.XnG2QY73jemC2zrJLgjENQlAxxX0pID4WJMiglDCmPog.PNG/02.png?type=w966",
    galleryColorClass: "text-blue-500",
    galleryImages: [
      "https://i.ibb.co/bgbk71Zb/seaflow-18.png",
      "https://i.ibb.co/bZ4SBpD/seaflow-17.png",
      "https://i.ibb.co/ccwFbzsS/seaflow-16.png",
      "https://i.ibb.co/GQWGfYRM/seaflow-15.png",
      "https://i.ibb.co/xqZK0gCx/seaflow-14.png",
      "https://i.ibb.co/tMHgXg1C/seaflow-13.png",
      "https://i.ibb.co/bjkXKqFh/seaflow-12.png",
      "https://i.ibb.co/d4SSnvmR/seaflow-11.png",
      "https://i.ibb.co/pvWd0Crk/seaflow-10.png",
      "https://i.ibb.co/LhvM3hD5/seaflow-9.png",
      "https://i.ibb.co/PsssXvQw/seaflow-8.png",
      "https://i.ibb.co/MDtxbtV9/seaflow-7.png",
      "https://i.ibb.co/XNPp3G7/seaflow-6.png",
      "https://i.ibb.co/spskXTdD/seaflow-5.png",
      "https://i.ibb.co/Qv83mtVj/seaflow-4.png",
      "https://i.ibb.co/WWFgjk0Y/seaflow-3.png",
      "https://i.ibb.co/QF16yvpj/seaflow-2.png",
      "https://i.ibb.co/9mTCKDgb/seaflow-1.png"
    ]
  }
];